[package]
name = "server"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "server"
path = "src/main.rs"

[dependencies]
game_server = { workspace = true }
bevy = { workspace = true, features = ["3d"] }
tracing-subscriber = { workspace = true }
