[package]
name = "client"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "client"
path = "src/main.rs"

[dependencies]
game_client = { workspace = true }
bevy = { workspace = true, features = ["3d", "ui", "default_font"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
bevy = { workspace = true, features = ["webgl2"] }
getrandom_0_4 = { package = "getrandom", version = "0.4", features = ["wasm_js"] }
getrandom_0_3 = { package = "getrandom", version = "0.3", features = ["wasm_js"] }
getrandom_0_2 = { package = "getrandom", version = "0.2", features = ["js"] }
