[package]
name = "game_client"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
bevy = { workspace = true, features = ["3d"] }
game_core = { workspace = true }
game_protocol = { workspace = true }
player = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
lightyear = { workspace = true, features = ["client", "udp", "netcode", "std", "replication", "interpolation"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
lightyear = { workspace = true, features = ["client", "netcode", "replication", "interpolation", "std", "webtransport", "websocket"] }
web-sys = { version = "0.3", features = ["Window", "Location"] }
getrandom = { version = "0.3", features = ["wasm_js"] }
aeronet_websocket = "0.21.0"

[dev-dependencies]
serde_json = "1"
