[package]
name = "game_server"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
bevy = { workspace = true, features = ["3d", "bevy_state"] }
lightyear = { workspace = true, features = ["server", "udp", "netcode", "crossbeam", "replication", "interpolation"] }
game_core = { workspace = true }
game_protocol = { workspace = true }
player = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
serde_json = "1"
bevy_replicon = "0.41"
