[package]
name = "game_server"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
bevy = { workspace = true, features = ["3d", "bevy_state"] }
lightyear = { workspace = true, features = ["server", "udp", "netcode", "crossbeam", "replication", "interpolation", "webtransport", "webtransport_self_signed", "websocket"] }
game_core = { workspace = true }
game_protocol = { workspace = true }
player = { workspace = true }
tracing = { workspace = true }
aeronet_websocket.workspace = true
aeronet_webtransport.workspace = true
rustls-pemfile.workspace = true

[dev-dependencies]
serde_json.workspace = true
bevy_replicon.workspace = true
