[package]
name = "housing"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
bevy = { workspace = true, features = ["3d"] }
lightyear = { workspace = true, features = ["replication"] }
game_core = { workspace = true }
game_protocol = { workspace = true }
avian3d = { version = "0.7", default-features = false, features = ["3d", "parry-f32"] }

[dev-dependencies]
serde_json.workspace = true
player = { workspace = true }
