[package]
name = "quests"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bevy = { workspace = true, features = ["bevy_state"] }
lightyear = { workspace = true }
serde = { workspace = true }
game_core = { workspace = true }
game_protocol = { workspace = true }
game_persistence = { workspace = true }
social = { workspace = true }
player = { workspace = true }
resources = { workspace = true }
tracing = { workspace = true }
