[package]
name = "social"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
bevy = { workspace = true, features = ["3d"] }
lightyear = { workspace = true, features = ["replication"] }
game_core = { workspace = true }
game_protocol = { workspace = true }
